name: Tests

on: push

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
            dotnet-version: '5.0.x'
      - run: dotnet test
